### ISSUE TITLE
Generator not working on windows.

### ISSUE THREAD

**Issue by uzair-ali-10p** [umayr/generator-ng-bat#7]
Node v4.2.2

Error:
```
λ yo ng-bat
module.js:339
    throw err;
    ^

Error: Cannot find module '../../utils'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\uzair.ali\AppData\Roaming\nvm\v4.2.2\node_modules\generator-ng-bat\generators\app\index.js:8:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by uzair-ali-10p** [comment]
Its not windows only issue.

npm is not copying `utils.js`
